### ISSUE TITLE
Introduction à RxJS [Addendum] WebsocketSubject

### ISSUE THREAD

**Issue by kael** [JulienPradet/blog-posts#8]
Il existe un `WebsocketSubject` qui peut gèrer la reconnexion et s'utilise ainsi:

```js
 let subject = Observable.webSocket('ws://localhost:8081');
 subject.subscribe(
    (msg) => console.log('message received: ' + msg),
    (err) => console.log(err),
    () => console.log('complete')
  );
// Reconnexion automatique, voire aussi avec 'retryWhen'
subject.retry().subscribe(...);
// Envoi de message
subject.next(JSON.stringify({ op: 'hello' }));
```

via: [StackOverflow](https://stackoverflow.com/a/44067972)

**Comment by JulienPradet** [comment]
Tout à fait !

Et d'ailleurs, il existe la même chose pour des requêtes ajax (qui est [codé](https://github.com/ReactiveX/rxjs/blob/master/src/observable/dom/AjaxObservable.ts) mais pas [documenté](https://github.com/ReactiveX/rxjs/issues/2656)), qui a l'avantage par rapport à ce que j'ai écrit dans l'article de permettre d'abort des requêtes quand on se désinscrit d'un Observable.

Le but de cette section était surtout d'expliquer *comment* créer des observables. Mais je vais rajouter une mention vers ces opérateurs en commentaire pour éviter aux gens de réécrire ces obserables pour rien.

Merci pour le pointeur :) Si tu en as d'autres, n'hésite pas.

**Comment by JulienPradet** [comment]
J'ai enfin pris le temps d'ajouter une note à ce sujet. Merci pour la remontée d'info :)
